# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa9dd80738ecfe1320ec5ed57a487cee71a5a2be8e8bfe7e1eeb37a6a66b65b1db1820982f67673a6b1949fa0abbeec5f59df46ac2b7cb4ea687574bf2f80d59

test:
  secret_key_base: c4f6c522fc1c154a55dcd62ba7f834bb806cdf0efeb40b3e78d7c89223250dac2ce1737e65e6910ce240264324d729cd68a539c7951af406bdaf644bca6410dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
